import { CheckCircle, Clock, Coffee, Heart, Plane, UserX } from "lucide-react";

export const estadosConductor = [
  {
    key: "servicio",
    label: "En Servicio",
    description: "Conductor activo prestando servicio",
    color: "success" as const,
    icon: CheckCircle,
    bgColor: "bg-green-50",
    textColor: "text-green-700",
    borderColor: "border-green-200",
  },
  {
    key: "disponible",
    label: "Disponible",
    description: "Conductor disponible para asignar",
    color: "primary" as const,
    icon: Clock,
    bgColor: "bg-blue-50",
    textColor: "text-blue-700",
    borderColor: "border-blue-200",
  },
  {
    key: "descanso",
    label: "Descanso",
    description: "Conductor en período de descanso",
    color: "secondary" as const,
    icon: Coffee,
    bgColor: "bg-gray-50",
    textColor: "text-gray-700",
    borderColor: "border-gray-200",
  },
  {
    key: "vacaciones",
    label: "Vacaciones",
    description: "Conductor en período vacacional",
    color: "warning" as const,
    icon: Plane,
    bgColor: "bg-amber-50",
    textColor: "text-amber-700",
    borderColor: "border-amber-200",
  },
  {
    key: "incapacidad",
    label: "Incapacidad",
    description: "Conductor con incapacidad médica",
    color: "danger" as const,
    icon: Heart,
    bgColor: "bg-red-50",
    textColor: "text-red-700",
    borderColor: "border-red-200",
  },
  {
    key: "desvinculado",
    label: "Desvinculado",
    description: "Conductor desvinculado de la empresa",
    color: "default" as const,
    icon: UserX,
    bgColor: "bg-gray-100",
    textColor: "text-gray-600",
    borderColor: "border-gray-300",
  },
];
